#!/usr/bin/env python3
"""
CortexInferno Model Converter
─────────────────────────────
Converts ONNX models to quantized INT8 C-header files
ready for deployment with the CortexInferno runtime.

Usage:
    python model_converter.py --model model.onnx --output weights.h --name mnist
    python model_converter.py --demo  # Generate a demo MNIST model
"""

import argparse
import numpy as np
import os
import sys
import struct
from pathlib import Path

def compute_quant_params(data: np.ndarray):
    """Compute per-tensor affine quantization params (INT8)."""
    min_val = min(float(data.min()), 0.0)
    max_val = max(float(data.max()), 0.0)
    scale = (max_val - min_val) / 255.0
    if scale == 0:
        scale = 1.0
    zp = int(round(-min_val / scale))
    zp = max(0, min(255, zp))
    return scale, zp

def quantize_int8(data: np.ndarray, scale: float, zp: int) -> np.ndarray:
    q = np.round(data / scale) + zp
    return np.clip(q, -128, 127).astype(np.int8)

def generate_c_header(model_name: str, layers: list, output_path: str):
    """Generate a C++ header with quantized weights and model graph."""
    with open(output_path, 'w') as f:
        f.write(f"#pragma once\n")
        f.write(f"// Auto-generated by CortexInferno Model Converter\n")
        f.write(f"// Model: {model_name}\n")
        f.write(f"// DO NOT EDIT MANUALLY\n\n")
        f.write(f"#include <cstdint>\n\n")
        f.write(f"namespace {model_name}_model {{\n\n")

        for i, layer in enumerate(layers):
            name = layer['name']
            data = layer['data']
            shape = layer['shape']
            scale = layer['scale']
            zp = layer['zp']

            # Write weight array
            flat = data.flatten()
            f.write(f"// Layer {i}: {name} | shape={shape} | scale={scale:.6f} zp={zp}\n")
            f.write(f"alignas(16) const int8_t {name}_weights[{len(flat)}] = {{\n")
            for j in range(0, len(flat), 16):
                chunk = flat[j:j+16]
                vals = ', '.join(f'{v:4d}' for v in chunk)
                f.write(f"    {vals},\n")
            f.write(f"}};\n\n")

            # Write bias if present
            if 'bias' in layer:
                bias = layer['bias']
                f.write(f"const int32_t {name}_bias[{len(bias)}] = {{\n")
                for j in range(0, len(bias), 8):
                    chunk = bias[j:j+8]
                    vals = ', '.join(f'{v}' for v in chunk)
                    f.write(f"    {vals},\n")
                f.write(f"}};\n\n")

        # Write model config struct
        f.write(f"struct ModelConfig {{\n")
        f.write(f"    int num_layers = {len(layers)};\n")
        for i, layer in enumerate(layers):
            f.write(f"    // Layer {i}: {layer['name']} type={layer['type']}\n")
        f.write(f"}};\n\n")
        f.write(f"constexpr ModelConfig config;\n\n")
        f.write(f"}} // namespace {model_name}_model\n")

    print(f"✅ Generated {output_path} ({os.path.getsize(output_path)} bytes)")

def convert_onnx(model_path: str, output_path: str, model_name: str):
    """Convert an ONNX model to CortexInferno C-header."""
    try:
        import onnx
        from onnx import numpy_helper
    except ImportError:
        print("❌ Install onnx: pip install onnx")
        sys.exit(1)

    model = onnx.load(model_path)
    graph = model.graph

    layers = []
    for node in graph.node:
        for inp_name in node.input:
            for init in graph.initializer:
                if init.name == inp_name:
                    data = numpy_helper.to_array(init)
                    scale, zp = compute_quant_params(data)
                    q_data = quantize_int8(data, scale, zp)
                    safe_name = init.name.replace('.', '_').replace('/', '_')

                    layer_info = {
                        'name': safe_name,
                        'data': q_data,
                        'shape': list(data.shape),
                        'scale': scale,
                        'zp': zp,
                        'type': node.op_type
                    }

                    # Check for bias
                    for bias_name in node.input:
                        for bias_init in graph.initializer:
                            if bias_init.name == bias_name and bias_init.name != init.name:
                                bias_data = numpy_helper.to_array(bias_init)
                                layer_info['bias'] = bias_data.astype(np.int32).flatten().tolist()

                    layers.append(layer_info)

    generate_c_header(model_name, layers, output_path)

def generate_demo_model(output_path: str):
    """Generate a tiny demo MNIST model (random weights) for testing."""
    print("🎲 Generating demo MNIST model with random weights...")

    layers = []

    # Dense 1: 784 → 128
    w1 = np.random.randn(128, 784).astype(np.float32) * 0.05
    s1, z1 = compute_quant_params(w1)
    layers.append({
        'name': 'dense1', 'data': quantize_int8(w1, s1, z1),
        'shape': [128, 784], 'scale': s1, 'zp': z1, 'type': 'Gemm',
        'bias': np.zeros(128, dtype=np.int32).tolist()
    })

    # Dense 2: 128 → 10
    w2 = np.random.randn(10, 128).astype(np.float32) * 0.1
    s2, z2 = compute_quant_params(w2)
    layers.append({
        'name': 'dense2', 'data': quantize_int8(w2, s2, z2),
        'shape': [10, 128], 'scale': s2, 'zp': z2, 'type': 'Gemm',
        'bias': np.zeros(10, dtype=np.int32).tolist()
    })

    generate_c_header("mnist", layers, output_path)

def main():
    parser = argparse.ArgumentParser(description='CortexInferno Model Converter')
    parser.add_argument('--model', type=str, help='Path to ONNX model')
    parser.add_argument('--output', type=str, default='weights.h', help='Output C header')
    parser.add_argument('--name', type=str, default='model', help='Model namespace name')
    parser.add_argument('--demo', action='store_true', help='Generate demo model')
    args = parser.parse_args()

    if args.demo:
        generate_demo_model(args.output)
    elif args.model:
        convert_onnx(args.model, args.output, args.name)
    else:
        parser.print_help()

if __name__ == '__main__':
    main()